// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veterinaria_Genesis_DB.Data;

#nullable disable

namespace VeterinariaProyecto.Migrations
{
    [DbContext(typeof(VeterinariaContext))]
    partial class VeterinariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCargo")
                        .HasName("PK__Cargo__6C9856250ACFF26F");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int");

                    b.Property<int?>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdCita")
                        .HasName("PK__Cita__394B02024E0CB2EA");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdTratamiento");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Dni")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D594664230906588");

                    b.HasIndex(new[] { "Dni" }, "UQ__Cliente__C0308575D20E1AB0")
                        .IsUnique()
                        .HasFilter("[Dni] IS NOT NULL");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<int?>("IdCargo")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__Empleado__CE6D8B9E84A6F89E");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEspecialidad")
                        .HasName("PK__Especial__693FA0AFF6CB8E08");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Especie", b =>
                {
                    b.Property<int>("IdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecie"));

                    b.Property<string>("NombreEspecie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEspecie")
                        .HasName("PK__Especie__08BEEA3E94138236");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.HasKey("IdFactura")
                        .HasName("PK__Factura__50E7BAF142100119");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.FacturaProducto", b =>
                {
                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdFactura", "IdProducto");

                    b.HasIndex("IdProducto");

                    b.ToTable("FacturaProducto");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<bool?>("Esterilizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int");

                    b.Property<int>("IdRaza")
                        .HasColumnType("int");

                    b.Property<int>("IdSexo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdMascota")
                        .HasName("PK__Mascota__5C9C26F0D5B38D71");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdRaza");

                    b.HasIndex("IdSexo");

                    b.ToTable("Mascota");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__09889210617ED440");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdProveedor")
                        .HasName("PK__Proveedo__E8B631AFC041219D");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Raza", b =>
                {
                    b.Property<int>("IdRaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRaza"));

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int");

                    b.Property<string>("NombreRaza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRaza")
                        .HasName("PK__Raza__8F06EB28D553DF48");

                    b.HasIndex("IdEspecie");

                    b.HasIndex(new[] { "NombreRaza", "IdEspecie" }, "UQ_Raza_Especie")
                        .IsUnique();

                    b.ToTable("Raza");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Sexo", b =>
                {
                    b.Property<int>("IdSexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSexo"));

                    b.Property<string>("NombreSexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdSexo")
                        .HasName("PK__Sexo__A7739FA2A5E6C3EC");

                    b.ToTable("Sexo");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTratamiento")
                        .HasName("PK__Tratamie__5CB7E7532A06EE80");

                    b.ToTable("Tratamiento");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97C9D4AFC5");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ__Usuario__6B0F5AE0B6A027EA")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Cita", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Mascota", "IdMascotaNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("IdMascota")
                        .IsRequired()
                        .HasConstraintName("FK_Cita_Mascota");

                    b.HasOne("Veterinaria_Genesis_DB.Models.Tratamiento", "IdTratamientoNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("IdTratamiento")
                        .HasConstraintName("FK_Cita_Tratamiento");

                    b.Navigation("IdMascotaNavigation");

                    b.Navigation("IdTratamientoNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Empleado", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Cargo", "IdCargoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdCargo")
                        .HasConstraintName("FK_Empleado_Cargo");

                    b.HasOne("Veterinaria_Genesis_DB.Models.Especialidad", "IdEspecialidadNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdEspecialidad")
                        .HasConstraintName("FK_Empleado_Especialidad");

                    b.Navigation("IdCargoNavigation");

                    b.Navigation("IdEspecialidadNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Factura", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Cliente");

                    b.HasOne("Veterinaria_Genesis_DB.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Empleado");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.FacturaProducto", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Factura", "IdFacturaNavigation")
                        .WithMany("FacturaProductos")
                        .HasForeignKey("IdFactura")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaProducto_Factura");

                    b.HasOne("Veterinaria_Genesis_DB.Models.Producto", "IdProductoNavigation")
                        .WithMany("FacturaProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_FacturaProducto_Producto");

                    b.Navigation("IdFacturaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Mascota", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Mascota_Cliente");

                    b.HasOne("Veterinaria_Genesis_DB.Models.Especie", "IdEspecieNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdEspecie")
                        .IsRequired()
                        .HasConstraintName("FK_Mascota_Especie");

                    b.HasOne("Veterinaria_Genesis_DB.Models.Raza", "IdRazaNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdRaza")
                        .IsRequired()
                        .HasConstraintName("FK_Mascota_Raza");

                    b.HasOne("Veterinaria_Genesis_DB.Models.Sexo", "IdSexoNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdSexo")
                        .IsRequired()
                        .HasConstraintName("FK_Mascota_Sexo");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEspecieNavigation");

                    b.Navigation("IdRazaNavigation");

                    b.Navigation("IdSexoNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Producto", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Proveedor");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Raza", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Especie", "IdEspecieNavigation")
                        .WithMany("Razas")
                        .HasForeignKey("IdEspecie")
                        .IsRequired()
                        .HasConstraintName("FK_Raza_Especie");

                    b.Navigation("IdEspecieNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Usuario", b =>
                {
                    b.HasOne("Veterinaria_Genesis_DB.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Empleado");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Empleado", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Especialidad", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Especie", b =>
                {
                    b.Navigation("Mascota");

                    b.Navigation("Razas");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Factura", b =>
                {
                    b.Navigation("FacturaProductos");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Mascota", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Producto", b =>
                {
                    b.Navigation("FacturaProductos");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Raza", b =>
                {
                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Sexo", b =>
                {
                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("Veterinaria_Genesis_DB.Models.Tratamiento", b =>
                {
                    b.Navigation("Cita");
                });
#pragma warning restore 612, 618
        }
    }
}
